name: CI

on:
  push:
    branches:
      - main
      - next
      - v2
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: typecheck
        run: pnpm lint
      - name: test
        run: pnpm test:ci
      - name: build
        run: pnpm build
